language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.10.*
  - DJANGO_VERSION=1.11.*
# command to install requirements
install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION
script:
 - pep8 memento
 - pyflakes memento
 - coverage run setup.py test
after_success:
  - coveralls
